name: matching_app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
    sdk: '>=3.0.5 <4.0.0'
dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter
    json_serializable: ^6.6.1
    flutter_redux: ^0.8.2
    redux: ^5.0.0
    cupertino_icons: ^1.0.2
    provider: ^6.0.0
    flutter_svg: ^2.0.7
    flutter_cupertino_date_picker_fork: ^1.0.7
    filter_list: ^1.0.2
    image_picker: ^0.8.9
    image_cropper: ^5.0.0
    scroll_page_view: ^1.0.2
    carousel_slider: ^4.2.1
    carousel_indicator: ^1.0.6
    modal_bottom_sheet: ^3.0.0-pre
dev_dependencies:
    flutter_test:
        sdk: flutter
    build_runner: any
    flutter_lints: ^2.0.0
flutter:
    uses-material-design: true
  # To add assets to your application, add an assets section, like this:
    assets:
        - assets/images/
        - assets/images/icons/
        - assets/images/identity/
        - assets/images/community/
        - assets/images/login/
        - assets/images/svg/
        - assets/images/status/
        - assets/images/main/
        - assets/images/users/
  #  - images/a_dot_ham.jpeg
      
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
      
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
      
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages